/**
 * PROFESSIONAL FORECAST SERVICE — CVK-1100
 * =============================================================================
 * Issues professional trading forecasts with full legal responsibility chain.
 *
 * CORE PRINCIPLE (per Darryl's instruction):
 *   "If someone uses the information the platform produces they assume
 *    responsibility for sign off fully and the forecast or any information
 *    provided does not become legal or binding in any way until this is
 *    completed and returned to the platform for confirmation where the
 *    platform will identify the qualified professional to ensure that person
 *    has the qualifications required to sign the relevant certificate."
 *
 * RESPONSIBILITY CHAIN:
 *   Step 1 — PLATFORM generates forecast (AI + Oracle 12-pillar)
 *   Step 2 — DISCLAIMER issued: information only, NOT binding, user assumes
 *             full responsibility for any action taken
 *   Step 3 — USER returns forecast to platform for confirmation sign-off
 *   Step 4 — PLATFORM identifies qualified professional for the domain
 *   Step 5 — QUALIFIED PROFESSIONAL verifies credentials + signs certificate
 *   Step 6 — CERTIFICATE issued: legally valid, traceable, audit-trailed
 *   Step 7 — V10 gate records the signed certificate as A1 evidence
 *
 * FORECAST TYPES:
 *   TRADING_TIP       — Short actionable signal (BUY/SELL/HOLD + entry/SL/TP)
 *   MARKET_FORECAST   — Directional bias for symbol over 1H/4H/D/W timeframe
 *   RISK_ASSESSMENT   — Probability and risk/reward analysis
 *   SECTOR_OUTLOOK    — Multi-asset class view (forex/crypto/stock sector)
 *   MACRO_BRIEF       — Central bank stance + macro environment summary
 *
 * LEGAL FRAMEWORK:
 *   - MiFID II Article 24: Best execution + suitability
 *   - FCA COBS 12: Recommendations and research
 *   - ESMA Guidelines on product governance
 *   - Consumer Duty (FCA PS22/9): fair value + consumer outcomes
 *   - GDPR Article 22: automated decision-making disclosure
 *
 * CVK-1100: Every forecast is scored, hashed, and gated before publication.
 */

import crypto from 'crypto';

// ── Types ─────────────────────────────────────────────────────────────────────

export type ForecastType =
  | 'TRADING_TIP'
  | 'MARKET_FORECAST'
  | 'RISK_ASSESSMENT'
  | 'SECTOR_OUTLOOK'
  | 'MACRO_BRIEF';

export type ForecastStatus =
  | 'DRAFT'           // Generated by AI, not yet returned for sign-off
  | 'PENDING_SIGNOFF' // User returned to platform, awaiting professional
  | 'UNDER_REVIEW'    // Qualified professional is reviewing
  | 'SIGNED'          // Professional signed — legally valid
  | 'REJECTED'        // Professional rejected — not to be used
  | 'EXPIRED';        // Expired before sign-off (24h for trading tips)

export type ResponsibilityParty =
  | 'AI_PLATFORM'     // Initial generation
  | 'END_USER'        // User who received and may act on the information
  | 'QUALIFIED_PROFESSIONAL'; // Licensed signer

export type ForecastTimeframe = '1H' | '4H' | 'D' | 'W' | 'M';

export interface ResponsibilityLink {
  party:        ResponsibilityParty;
  timestamp:    string;
  action:       string;
  description:  string;
  ip_hash?:     string;   // SHA-256 hash of IP — privacy-compliant
  signature?:   string;   // SHA-256 of party + timestamp + forecast_id
  credential?:  string;   // Professional credential ID (for QUALIFIED_PROFESSIONAL)
}

export interface ForecastDisclaimer {
  version:              string;    // e.g. "ORB-DISCLAIMER-v2.1"
  issued_at:            string;
  language:             string;    // ISO 639-1 e.g. "en"

  // Core statements
  not_financial_advice: string;
  user_responsibility:  string;
  no_guarantee:         string;
  risk_warning:         string;
  regulatory_status:    string;
  ai_limitation:        string;
  sign_off_required:    string;
  gdpr_article_22:      string;

  // User acknowledgement (must be explicitly accepted before user acts)
  user_must_acknowledge: string[];
  acceptance_required:   boolean;
}

export interface ProfessionalForecast {
  // Identity
  forecast_id:      string;          // FCST-{type}-{ts}-{random6}
  forecast_type:    ForecastType;
  status:           ForecastStatus;

  // Subject
  symbol:           string;
  asset_class:      'forex' | 'crypto' | 'stock' | 'macro';
  timeframe:        ForecastTimeframe;

  // Forecast content
  direction:        'BULLISH' | 'BEARISH' | 'NEUTRAL';
  conviction:       'HIGH' | 'MEDIUM' | 'LOW';
  oracle_score:     number;          // 0–100 from Oracle 12-pillar

  // Trading tip fields (when type = TRADING_TIP)
  tip?: {
    action:         'BUY' | 'SELL' | 'HOLD';
    entry_price:    number;
    stop_loss:      number;
    take_profit_1:  number;
    take_profit_2:  number;
    risk_reward:    number;
    position_size_pct: number;
    pip_value?:     number;
  };

  // Forecast narrative
  summary:          string;          // 1–2 sentence human-readable summary
  rationale:        string[];        // Bullet points: key drivers
  risks:            string[];        // Key risk factors
  key_levels:       { label: string; price: number; type: 'support' | 'resistance' | 'target' }[];

  // Macro context (always populated)
  macro_context: {
    central_bank_stance: string;
    smart_money_bias:    string;
    market_session:      string;
    volatility_regime:   string;
  };

  // V10 certification
  signal_id:        string;          // source signal ID
  veritech_cert_id: string;
  data_hash:        string;          // SHA-256 of forecast content

  // Legal / responsibility chain
  disclaimer:       ForecastDisclaimer;
  responsibility_chain: ResponsibilityLink[];

  // Timestamps
  generated_at:     string;
  expires_at:       string;         // 24H for TRADING_TIP, 7D for MARKET_FORECAST
  signed_at?:       string;
  signed_by?:       string;         // Qualified professional credential ID

  // V10 gate
  v10_certified:    boolean;
  cert_id?:         string;
}

export interface SignOffRequest {
  forecast_id:      string;
  requester_id:     string;         // Who is requesting sign-off
  requester_type:   'USER' | 'SYSTEM';
  reason:           string;
  user_acknowledgement: boolean;    // MUST be true — user accepted disclaimer
  submitted_at:     string;
  ip_hash?:         string;
}

export interface SignOffResult {
  success:          boolean;
  forecast_id:      string;
  status:           ForecastStatus;
  assigned_professional?: {
    credential_id:  string;
    name:           string;
    qualification:  string;
    domain:         string;
  };
  message:          string;
  next_step:        string;
}

// ── Constants ─────────────────────────────────────────────────────────────────

const DISCLAIMER_VERSION = 'ORB-DISCLAIMER-v2.1';

const EXPIRY_HOURS: Record<ForecastType, number> = {
  TRADING_TIP:     24,
  MARKET_FORECAST: 168,  // 7 days
  RISK_ASSESSMENT: 48,
  SECTOR_OUTLOOK:  168,
  MACRO_BRIEF:     72,
};

// ── Disclaimer Factory ────────────────────────────────────────────────────────

function buildDisclaimer(forecastType: ForecastType): ForecastDisclaimer {
  return {
    version:   DISCLAIMER_VERSION,
    issued_at: new Date().toISOString(),
    language:  'en',

    not_financial_advice:
      'THIS FORECAST IS FOR INFORMATIONAL AND EDUCATIONAL PURPOSES ONLY. ' +
      'It does NOT constitute financial advice, investment advice, trading advice, ' +
      'or any other form of advice. No part of this forecast should be construed as ' +
      'a recommendation to buy, sell, or hold any financial instrument.',

    user_responsibility:
      'BY ACCESSING OR USING THIS FORECAST, YOU ACCEPT FULL AND SOLE RESPONSIBILITY ' +
      'for any trading or investment decisions you make, including all losses that may result. ' +
      'The Orb AI Universe, Playbook Corporation, and all affiliated entities expressly disclaim ' +
      'all liability for any losses, damages, or consequences arising from use of this information.',

    no_guarantee:
      'Past performance, backtested results, and historical accuracy statistics do NOT ' +
      'guarantee future results. All trading involves risk. You may lose some or all of ' +
      'your invested capital. Never trade with money you cannot afford to lose.',

    risk_warning:
      '⚠️ HIGH RISK WARNING: Trading foreign exchange, cryptocurrencies, contracts for difference (CFDs), ' +
      'and other leveraged financial products carries a HIGH RISK OF LOSS and is not suitable for ' +
      'all investors. Leverage can work against you as well as for you.',

    regulatory_status:
      'Orb AI Universe / Playbook Corporation is NOT authorised by the Financial Conduct Authority (FCA), ' +
      'the Securities and Exchange Commission (SEC), the European Securities and Markets Authority (ESMA), ' +
      'or any other regulatory body to provide investment advice. This platform provides AI-assisted ' +
      'analytical information only.',

    ai_limitation:
      'This forecast is generated by an artificial intelligence system (Architecture B, Oracle 12-pillar). ' +
      'AI systems can and do make errors. The AI has no knowledge of events occurring after its data cutoff. ' +
      'AI-generated analysis is a mathematical exercise, not human judgement. Do not rely solely on AI output.',

    sign_off_required:
      'THIS FORECAST DOES NOT BECOME LEGALLY BINDING OR VALID FOR PROFESSIONAL USE until it has been ' +
      'RETURNED TO THIS PLATFORM for confirmation, and a QUALIFIED PROFESSIONAL with the required ' +
      'credentials for this domain has reviewed and signed the associated certificate. ' +
      'Until that process is completed, this document is NOT a professional recommendation.',

    gdpr_article_22:
      'Pursuant to GDPR Article 22, you have the right not to be subject to decisions based solely on ' +
      'automated processing. This forecast is produced by automated AI analysis. You may request ' +
      'human review at any time via the sign-off process. Contact: compliance@playbook.ai',

    user_must_acknowledge: [
      'I understand this is platform-generated analysis, NOT financial advice',
      'I accept full personal responsibility for any trading decisions I make',
      'I understand no guarantee of profit is made or implied',
      'I confirm I am not relying on this as a licensed professional recommendation',
      'I understand this forecast requires qualified professional sign-off to become legally valid',
      'I accept the risk warning and understand trading involves risk of total capital loss',
      `I have read and understood the full disclaimer (${DISCLAIMER_VERSION})`,
    ],
    acceptance_required: true,
  };
}

// ── Forecast Service ──────────────────────────────────────────────────────────

class ProfessionalForecastService {

  private forecasts = new Map<string, ProfessionalForecast>();
  private signOffQueue = new Map<string, SignOffRequest>();

  // ── Generate a professional forecast from a trading signal ─────────────────

  generateFromSignal(
    signal: any,
    oracle:  any,
    calibration: any,
    forecastType: ForecastType = 'TRADING_TIP',
    timeframe: ForecastTimeframe = '1H',
  ): ProfessionalForecast {

    const now       = new Date();
    const expiresAt = new Date(now.getTime() + EXPIRY_HOURS[forecastType] * 3600 * 1000);
    const forecastId = `FCST-${forecastType.slice(0,3)}-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;

    // Direction from signal
    const direction: 'BULLISH' | 'BEARISH' | 'NEUTRAL' =
      signal.action === 'BUY'  ? 'BULLISH' :
      signal.action === 'SELL' ? 'BEARISH' : 'NEUTRAL';

    // Conviction from oracle score
    const conviction: 'HIGH' | 'MEDIUM' | 'LOW' =
      (oracle?.score ?? signal.signal_score) >= 78 ? 'HIGH' :
      (oracle?.score ?? signal.signal_score) >= 60 ? 'MEDIUM' : 'LOW';

    // Build tip (for TRADING_TIP type)
    const tip = forecastType === 'TRADING_TIP' ? {
      action:            signal.action,
      entry_price:       signal.entry_price,
      stop_loss:         signal.stop_loss,
      take_profit_1:     signal.take_profit_1,
      take_profit_2:     signal.take_profit_2,
      risk_reward:       signal.risk_reward,
      position_size_pct: signal.position_size_pct,
      pip_value:         signal.pip_value,
    } : undefined;

    // Build rationale from layers
    const layers   = signal.layers || {};
    const rationale: string[] = [];
    if (layers.technical?.score) {
      rationale.push(`Technical confluence: ${layers.technical.score}/100 (RSI ${layers.technical.rsi?.toFixed(1) || 'N/A'}, trend: ${layers.technical.trend || 'MIXED'})`);
    }
    if (layers.volume?.signal) {
      rationale.push(`Volume: ${layers.volume.signal} (score: ${layers.volume.score}/100)`);
    }
    if (layers.momentum?.signal) {
      rationale.push(`Momentum: ${layers.momentum.signal} (score: ${layers.momentum.score}/100)`);
    }
    if (layers.pattern_layer?.pattern !== 'NONE') {
      rationale.push(`Pattern (DTW): ${layers.pattern_layer?.pattern || 'None'} — bias: ${layers.pattern_layer?.trade_bias || 'WAIT'} (confidence: ${layers.pattern_layer?.confidence || 0}%)`);
    }
    if (oracle?.pillars) {
      const p = oracle.pillars;
      rationale.push(`Oracle CB NLP: ${p.p7_cb_nlp?.toFixed(0) || 50}/100 | Smart Money: ${p.p8_smart_money?.toFixed(0) || 50}/100 | R:R quality: ${p.p9_risk_reward?.toFixed(0) || 50}/100`);
    }
    if (calibration?.calibrated_pct) {
      rationale.push(`PAV-calibrated confidence: ${calibration.calibrated_pct?.toFixed(1)}% (raw: ${signal.confidence_pct?.toFixed(1)}%, ECE-corrected)`);
    }

    // Risks
    const risks: string[] = [
      `Stop loss breach (${signal.stop_loss}) — ${signal.asset_class === 'forex' ? 'forex pip' : 'price'} exposure`,
      `Market session risk: ${signal.market_session || 'UNKNOWN'} — liquidity may be reduced`,
    ];
    if (signal.asset_class === 'crypto') risks.push('Crypto 24/7 volatility — unexpected gap risk');
    if (signal.asset_class === 'stock')  risks.push('Earnings/news event risk — check economic calendar');
    if ((oracle?.score || 0) < 65)       risks.push('Below-threshold Oracle score — conviction low, reduce position size');

    // Key levels
    const ta  = signal.technical_analysis?.support_resistance || [];
    const keyLevels = [
      { label: 'Entry', price: signal.entry_price, type: 'target' as const },
      { label: 'Stop Loss', price: signal.stop_loss, type: signal.action === 'BUY' ? 'support' as const : 'resistance' as const },
      { label: 'Target 1', price: signal.take_profit_1, type: signal.action === 'BUY' ? 'resistance' as const : 'support' as const },
      { label: 'Target 2', price: signal.take_profit_2, type: signal.action === 'BUY' ? 'resistance' as const : 'support' as const },
      ...ta.slice(0, 3).map((sr: any) => ({ label: sr.type === 'support' ? `S: ${sr.level}` : `R: ${sr.level}`, price: sr.level, type: sr.type })),
    ];

    // Macro context
    const macro_context = {
      central_bank_stance: signal.layers?.asset_specific?.notes?.[0] || 'Pending CB NLP feed',
      smart_money_bias:    'Pending COT data',
      market_session:      signal.market_session || 'UNKNOWN',
      volatility_regime:   (oracle?.pillars?.p4_asset_specific || 50) > 65 ? 'NORMAL' : 'ELEVATED',
    };

    // Summary
    const summary = `${signal.asset_class.toUpperCase()} ${signal.symbol} — ${direction} bias. ` +
      `Oracle score ${oracle?.score || signal.signal_score}/100 (${conviction} conviction). ` +
      `${forecastType === 'TRADING_TIP' ? `${signal.action} at ${signal.entry_price}, SL: ${signal.stop_loss}, TP1: ${signal.take_profit_1}.` : `${timeframe} timeframe directional view.`}`;

    // Responsibility chain — Step 1: AI Platform
    const responsibilityChain: ResponsibilityLink[] = [{
      party:       'AI_PLATFORM',
      timestamp:   now.toISOString(),
      action:      'FORECAST_GENERATED',
      description: `Oracle 12-pillar composite score: ${oracle?.score || signal.signal_score}. ` +
                   `PAV calibration: ${calibration?.calibrated_pct?.toFixed(1) || 'N/A'}%. ` +
                   `DTW pattern: ${layers.pattern_layer?.pattern || 'NONE'}. ` +
                   `VeriTech cert: ${signal.veritech_cert_id}. ` +
                   'AI analysis complete. Forecast in DRAFT status. ' +
                   'NOT legally valid until qualified professional sign-off.',
      signature:   crypto.createHash('sha256')
        .update(`AI_PLATFORM:${now.toISOString()}:${forecastId}`)
        .digest('hex').slice(0, 16).toUpperCase(),
    }];

    // Data hash — integrity proof
    const contentToHash = JSON.stringify({ symbol: signal.symbol, action: signal.action, oracle_score: oracle?.score, entry: signal.entry_price, sl: signal.stop_loss, tp1: signal.take_profit_1 });
    const dataHash = crypto.createHash('sha256').update(contentToHash).digest('hex');

    const forecast: ProfessionalForecast = {
      forecast_id:    forecastId,
      forecast_type:  forecastType,
      status:         'DRAFT',
      symbol:         signal.symbol,
      asset_class:    signal.asset_class,
      timeframe,
      direction,
      conviction,
      oracle_score:   oracle?.score || signal.signal_score,
      tip,
      summary,
      rationale,
      risks,
      key_levels:     keyLevels,
      macro_context,
      signal_id:      signal.signal_id,
      veritech_cert_id: signal.veritech_cert_id,
      data_hash:      dataHash,
      disclaimer:     buildDisclaimer(forecastType),
      responsibility_chain: responsibilityChain,
      generated_at:   now.toISOString(),
      expires_at:     expiresAt.toISOString(),
      v10_certified:  false,
    };

    this.forecasts.set(forecastId, forecast);
    return forecast;
  }

  // ── User returns forecast to platform for sign-off ─────────────────────────

  requestSignOff(req: SignOffRequest): SignOffResult {
    const forecast = this.forecasts.get(req.forecast_id);
    if (!forecast) {
      return {
        success:    false,
        forecast_id: req.forecast_id,
        status:     'EXPIRED',
        message:    `Forecast ${req.forecast_id} not found or expired.`,
        next_step:  'Generate a new forecast and return it within the expiry window.',
      };
    }

    if (new Date() > new Date(forecast.expires_at)) {
      forecast.status = 'EXPIRED';
      return {
        success:    false,
        forecast_id: req.forecast_id,
        status:     'EXPIRED',
        message:    `Forecast expired at ${forecast.expires_at}. Trading tips are valid for 24 hours only.`,
        next_step:  'Request a fresh signal and forecast.',
      };
    }

    if (!req.user_acknowledgement) {
      return {
        success:    false,
        forecast_id: req.forecast_id,
        status:     forecast.status,
        message:    'Sign-off rejected: user has not acknowledged the disclaimer. ' +
                    'All disclaimer points must be accepted before sign-off can proceed.',
        next_step:  'User must accept all disclaimer acknowledgement points.',
      };
    }

    // Step 2: Record user responsibility acceptance
    const userLink: ResponsibilityLink = {
      party:       'END_USER',
      timestamp:   req.submitted_at,
      action:      'SIGN_OFF_REQUESTED',
      description: `User ${req.requester_id} returned forecast for professional sign-off. ` +
                   'User accepted full responsibility disclaimer. Qualification check initiated.',
      ip_hash:     req.ip_hash,
      signature:   crypto.createHash('sha256')
        .update(`END_USER:${req.submitted_at}:${req.forecast_id}:${req.requester_id}`)
        .digest('hex').slice(0, 16).toUpperCase(),
    };
    forecast.responsibility_chain.push(userLink);
    forecast.status = 'PENDING_SIGNOFF';
    this.signOffQueue.set(req.forecast_id, req);

    return {
      success:     true,
      forecast_id: req.forecast_id,
      status:      'PENDING_SIGNOFF',
      message:     'Sign-off request received. Platform is identifying the qualified professional ' +
                   'for this forecast domain. You will be notified when review is complete.',
      next_step:   `GET /api/trading/forecast/${req.forecast_id}/status to monitor progress. ` +
                   'A qualified professional will be assigned within the SLA.',
    };
  }

  // ── Professional signs the forecast ───────────────────────────────────────

  professionalSignOff(
    forecastId: string,
    professional: { credential_id: string; name: string; qualification: string; domain: string },
    decision: 'SIGN' | 'REJECT',
    notes: string,
  ): { success: boolean; forecast?: ProfessionalForecast; cert_id?: string; message: string } {

    const forecast = this.forecasts.get(forecastId);
    if (!forecast) return { success: false, message: `Forecast ${forecastId} not found.` };
    if (forecast.status !== 'PENDING_SIGNOFF' && forecast.status !== 'UNDER_REVIEW') {
      return { success: false, message: `Forecast is in status ${forecast.status} — cannot sign.` };
    }

    const now = new Date().toISOString();

    // Step 3: Record professional action
    const proLink: ResponsibilityLink = {
      party:       'QUALIFIED_PROFESSIONAL',
      timestamp:   now,
      action:      decision === 'SIGN' ? 'FORECAST_SIGNED' : 'FORECAST_REJECTED',
      description: `${professional.name} (${professional.qualification}) ${decision === 'SIGN' ? 'SIGNED' : 'REJECTED'} forecast. ` +
                   `Domain: ${professional.domain}. Credential: ${professional.credential_id}. Notes: ${notes}`,
      credential:  professional.credential_id,
      signature:   crypto.createHash('sha256')
        .update(`QUALIFIED_PROFESSIONAL:${now}:${forecastId}:${professional.credential_id}`)
        .digest('hex').slice(0, 16).toUpperCase(),
    };
    forecast.responsibility_chain.push(proLink);

    if (decision === 'SIGN') {
      forecast.status   = 'SIGNED';
      forecast.signed_at = now;
      forecast.signed_by = professional.credential_id;
      forecast.v10_certified = true;

      // Issue certificate ID
      const certId = `V10-FCST-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;
      forecast.cert_id = certId;

      return {
        success:  true,
        forecast,
        cert_id:  certId,
        message:  `Forecast SIGNED by ${professional.name} (${professional.qualification}). ` +
                  `Certificate ${certId} issued. Forecast is now legally valid.`,
      };
    } else {
      forecast.status = 'REJECTED';
      return {
        success:  false,
        forecast,
        message:  `Forecast REJECTED by ${professional.name}. Reason: ${notes}. ` +
                  'This forecast must NOT be used for trading.',
      };
    }
  }

  // ── Retrieve forecast ──────────────────────────────────────────────────────

  getById(id: string): ProfessionalForecast | undefined {
    return this.forecasts.get(id);
  }

  getAll(limit = 50): ProfessionalForecast[] {
    return Array.from(this.forecasts.values())
      .sort((a, b) => new Date(b.generated_at).getTime() - new Date(a.generated_at).getTime())
      .slice(0, limit);
  }

  getPendingSignOff(): ProfessionalForecast[] {
    return Array.from(this.forecasts.values())
      .filter(f => f.status === 'PENDING_SIGNOFF' || f.status === 'UNDER_REVIEW');
  }

  getSigned(): ProfessionalForecast[] {
    return Array.from(this.forecasts.values()).filter(f => f.status === 'SIGNED');
  }

  getSignOffQueue(): SignOffRequest[] {
    return Array.from(this.signOffQueue.values());
  }

  stats() {
    const all = Array.from(this.forecasts.values());
    return {
      total:          all.length,
      draft:          all.filter(f => f.status === 'DRAFT').length,
      pending:        all.filter(f => f.status === 'PENDING_SIGNOFF').length,
      signed:         all.filter(f => f.status === 'SIGNED').length,
      rejected:       all.filter(f => f.status === 'REJECTED').length,
      expired:        all.filter(f => f.status === 'EXPIRED').length,
      by_type: {
        trading_tip:    all.filter(f => f.forecast_type === 'TRADING_TIP').length,
        market_forecast:all.filter(f => f.forecast_type === 'MARKET_FORECAST').length,
        risk_assessment:all.filter(f => f.forecast_type === 'RISK_ASSESSMENT').length,
      },
    };
  }
}

export const professionalForecastService = new ProfessionalForecastService();
export default professionalForecastService;
